<a href="https://colab.research.google.com/github/Usama55555/AI-Lab/blob/main/Covid19_Tweets_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [ ]:
dataset = pd.read_csv('/content/covid19_tweets.csv')
dataset

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,·èâ·é•‚òª’¨ÍÇÖœÆ,astroworld,wednesday addams as a disney princess keepin i...,2017-05-26 05:46:42,624,950,18775,False,2020-07-25 12:27:21,If I smelled the scent of hand sanitizers toda...,NaN,Twitter for iPhone,False
1,Tom Basile üá∫üá∏,"New York, NY","Husband, Father, Columnist & Commentator. Auth...",2009-04-16 20:06:23,2253,1677,24,True,2020-07-25 12:27:17,Hey @Yankees @YankeesPR and @MLB - wouldn't it...,NaN,Twitter for Android,False
2,Time4fisticuffs,"Pewee Valley, KY",#Christian #Catholic #Conservative #Reagan #Re...,2009-02-28 18:57:41,9275,9525,7254,False,2020-07-25 12:27:14,@diane3443 @wdunlap @realDonaldTrump Trump nev...,['COVID19'],Twitter for Android,False
3,ethel mertz,Stuck in the Middle,#Browns #Indians #ClevelandProud #[]_[] #Cavs ...,2019-03-07 01:45:06,197,987,1488,False,2020-07-25 12:27:10,@brookbanktv The one gift #COVID19 has give me...,['COVID19'],Twitter for iPhone,False
4,DIPR-J&K,Jammu and Kashmir,üñäÔ∏èOfficial Twitter handle of Department of Inf...,2017-02-12 06:45:15,101009,168,101,False,2020-07-25 12:27:08,25 July : Media Bulletin on Novel #CoronaVirus...,"['CoronaVirusUpdates', 'COVID19']",Twitter for Android,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
179103,AJIMATI AbdulRahman O.,"Ilorin, Nigeria",Animal Scientist|| Muslim|| Real Madrid/Chelsea,2013-12-30 18:59:19,412,1609,1062,False,2020-08-29 19:44:21,Thanks @IamOhmai for nominating me for the @WH...,['WearAMask'],Twitter for Android,False
179104,Jason,Ontario,When your cat has more baking soda than Ninja ...,2011-12-21 04:41:30,150,182,7295,False,2020-08-29 19:44:16,2020! The year of insanity! Lol! #COVID19 http...,['COVID19'],Twitter for Android,False
179105,BEEHEMOTH ‚è≥,üá®üá¶ Canada,‚öíÔ∏è The Architects of Free Trade ‚öíÔ∏è Really Did ...,2016-07-13 17:21:59,1623,2160,98000,False,2020-08-29 19:44:15,@CTVNews A powerful painting by Juan Lucena. I...,NaN,Twitter Web App,False
179106,Gary DelPonte,New York City,"Global UX UI Visual Designer. StoryTeller, Mus...",2009-10-27 17:43:13,1338,1111,0,False,2020-08-29 19:44:14,"More than 1,200 students test positive for #CO...",['COVID19'],Twitter for iPhone,False
179107,TUKY II,"Aliwal North, South Africa",TOKELO SEKHOPA | TUKY II | LAST BORN | EISH TU...,2018-04-14 17:30:07,97,1697,566,False,2020-08-29 19:44:08,I stop when I see a Stop\n\n@SABCNews\n@Izinda...,NaN,Twitter for Android,False

In [ ]:
label = LabelEncoder()
label.fit(dataset.user_location.drop_duplicates())
dataset.user_location = label.transform(dataset.user_location)

label.fit(dataset.user_description.drop_duplicates())
dataset.user_description = label.transform(dataset.user_description)

label.fit(dataset.user_verified.drop_duplicates())
dataset.user_verified = label.transform(dataset.user_verified)

label.fit(dataset.text.drop_duplicates())
dataset.text = label.transform(dataset.text)

label.fit(dataset.user_created.drop_duplicates())
dataset.user_created = label.transform(dataset.user_created)

label.fit(dataset.date.drop_duplicates())
dataset.date = label.transform(dataset.date)

label.fit(dataset.hashtags.drop_duplicates())
dataset.hashtags = label.transform(dataset.hashtags)

label.fit(dataset.source.drop_duplicates())
dataset.source = label.transform(dataset.source)

label.fit(dataset.is_retweet.drop_duplicates())
dataset.is_retweet = label.transform(dataset.is_retweet)

dataset

,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,24697,84799,66533,624,950,18775,0,13823,99649,52640,481,0
1,15312,34250,9144,2253,1677,24,1,13822,92396,52640,478,0
2,17090,866,6145,9275,9525,7254,0,13821,47834,13170,478,0
3,20577,744,76075,197,987,1488,0,13820,46918,13170,481,0
4,10551,88876,65129,101009,168,101,0,13819,28554,15094,478,0
...,...,...,...,...,...,...,...,...,...,...,...,...
179103,9918,10705,48654,412,1609,1062,0,126010,141614,37258,478,0
179104,16381,78099,34778,150,182,7295,0,126009,28322,13170,478,0
179105,26717,86784,61910,1623,2160,98000,0,126008,33644,52640,474,0
179106,15259,30900,16950,1338,1111,0,0,126007,116532,13170,481,0
179107,1563,67128,71213,97,1697,566,0,126006,97722,52640,478,0

In [ ]:
from numpy.random.mtrand import RandomState
X_lin = dataset.drop(['user_favourites'], axis = 1)
Y_lin = dataset[['user_favourites']]


X_lin_train, X_lin_test, Y_lin_train, Y_lin_test = train_test_split(X_lin, Y_lin, test_size=0.3, random_state=42)

In [ ]:
Linear_model = LinearRegression()
Linear_model.fit(X_lin_train, Y_lin_train)

LinearRegression()

In [ ]:
pred = Linear_model.predict(X_lin_test)
pred

array([[ 7271.60964614],
       [ 3432.82074067],
       [12234.06711745],
       ...,
       [29055.14898289],
       [16242.65686939],
       [14835.580377  ]])

In [ ]:
for idx, col_name in enumerate(X_lin_train.columns):
  print("The cofficient for {} is {}".format(col_name, Linear_model.coef_[0][idx]))

The cofficient for user_location is 0.09974478109287156
The cofficient for user_description is -0.0251837801856839
The cofficient for user_created is -0.1845024971185815
The cofficient for user_followers is -0.0008195284794983229
The cofficient for user_friends is 0.9297601082513642
The cofficient for user_verified is -10355.954223739242
The cofficient for date is -0.0001703390812306173
The cofficient for text is -0.028130156784898934
The cofficient for hashtags is -0.05212835186279163
The cofficient for source is 37.8436054354474
The cofficient for is_retweet is 0.0

In [35]:
intercept = Linear_model.intercept_[0]
intercept

9452.776794634938